//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsView.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 未登录.
        /// </summary>
        public static string Account_NotSignedIn {
            get {
                return ResourceManager.GetString("Account_NotSignedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 已登录.
        /// </summary>
        public static string Account_SignedIn {
            get {
                return ResourceManager.GetString("Account_SignedIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 账户信息暂时不可用.
        /// </summary>
        public static string Account_InfoUnavailable {
            get {
                return ResourceManager.GetString("Account_InfoUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 登录.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 退出登录.
        /// </summary>
        public static string Account_SignOut {
            get {
                return ResourceManager.GetString("Account_SignOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 用户 ID.
        /// </summary>
        public static string Account_UserIdLabel {
            get {
                return ResourceManager.GetString("Account_UserIdLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 邮箱.
        /// </summary>
        public static string Account_EmailLabel {
            get {
                return ResourceManager.GetString("Account_EmailLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 复制用户 ID.
        /// </summary>
        public static string Account_CopyUserId {
            get {
                return ResourceManager.GetString("Account_CopyUserId", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 复制邮箱.
        /// </summary>
        public static string Account_CopyEmail {
            get {
                return ResourceManager.GetString("Account_CopyEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 已复制.
        /// </summary>
        public static string Account_Copied {
            get {
                return ResourceManager.GetString("Account_Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the localized string similar to 复制失败.
        /// </summary>
        public static string Account_CopyFailed {
            get {
                return ResourceManager.GetString("Account_CopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 扩展诊断包.
        /// </summary>
        public static string C_DiagnosticExtended {
            get {
                return ResourceManager.GetString("C_DiagnosticExtended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 标准诊断包.
        /// </summary>
        public static string C_DiagnosticStandard {
            get {
                return ResourceManager.GetString("C_DiagnosticStandard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出全部数据.
        /// </summary>
        public static string C_ExportAllDataFileTitle {
            get {
                return ResourceManager.GetString("C_ExportAllDataFileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string C_ExportDiagnosticDataFileTitle {
            get {
                return ResourceManager.GetString("C_ExportDiagnosticDataFileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string C_ExportSettingsFileTitle {
            get {
                return ResourceManager.GetString("C_ExportSettingsFileTitle", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入全部数据.
        /// </summary>
        public static string C_ImportAllDataFileTitle {
            get {
                return ResourceManager.GetString("C_ImportAllDataFileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string C_ImportSettingsFileTitle {
            get {
                return ResourceManager.GetString("C_ImportSettingsFileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JSON 文件.
        /// </summary>
        public static string C_JsonFileType {
            get {
                return ResourceManager.GetString("C_JsonFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 更多选项....
        /// </summary>
        public static string C_MoreOptions {
            get {
                return ResourceManager.GetString("C_MoreOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出所有数据.
        /// </summary>
        public static string C_MoreOptions_ExportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即导出 SecRandom v3 全部非凭据数据、设置、插件和插件私有配置.
        /// </summary>
        public static string C_MoreOptions_ExportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportAllData_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string C_MoreOptions_ExportDiagnosticData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 立即导出脱敏的运行时信息和受限日志，用于排查问题.
        /// </summary>
        public static string C_MoreOptions_ExportDiagnosticData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportDiagnosticData_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出设置.
        /// </summary>
        public static string C_MoreOptions_ExportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 将当前设置导出为 SecRandom v3 配置文件，用于备份和迁移.
        /// </summary>
        public static string C_MoreOptions_ExportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ExportSettings_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string C_Announcements {
            get {
                return ResourceManager.GetString("C_Announcements", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 导入所有数据.
        /// </summary>
        public static string C_MoreOptions_ImportAllData {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅从 SecRandom v3 备份导入全部数据，导入前自动创建恢复快照.
        /// </summary>
        public static string C_MoreOptions_ImportAllData_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportAllData_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入设置.
        /// </summary>
        public static string C_MoreOptions_ImportSettings {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 仅从 SecRandom v3 配置文件导入设置，覆盖当前配置信息.
        /// </summary>
        public static string C_MoreOptions_ImportSettings_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_ImportSettings_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看日志.
        /// </summary>
        public static string C_MoreOptions_LogViewer {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看和管理程序日志文件.
        /// </summary>
        public static string C_MoreOptions_LogViewer_D {
            get {
                return ResourceManager.GetString("C_MoreOptions_LogViewer_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开应用目录.
        /// </summary>
        public static string C_MoreOptions_OpenAppDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenAppDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开数据目录.
        /// </summary>
        public static string C_MoreOptions_OpenDataDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenDataDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开日志目录.
        /// </summary>
        public static string C_MoreOptions_OpenLogDirectory {
            get {
                return ResourceManager.GetString("C_MoreOptions_OpenLogDirectory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 搜索设置....
        /// </summary>
        public static string C_SearchBox_Watermark {
            get {
                return ResourceManager.GetString("C_SearchBox_Watermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZIP 文件.
        /// </summary>
        public static string C_ZipFileType {
            get {
                return ResourceManager.GetString("C_ZipFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 标准诊断包包含全部经过脱敏处理的日志和运行时信息。扩展诊断包还包含脱敏设置快照、插件与档案数量摘要及脱敏崩溃报告。两种诊断包均不包含名单、历史原文、插件私有配置或安全凭据.
        /// </summary>
        public static string M_DiagnosticExportContent {
            get {
                return ResourceManager.GetString("M_DiagnosticExportContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出诊断数据.
        /// </summary>
        public static string M_DiagnosticExportTitle {
            get {
                return ResourceManager.GetString("M_DiagnosticExportTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导出失败。.
        /// </summary>
        public static string M_ExportFailed {
            get {
                return ResourceManager.GetString("M_ExportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已导出：{0}.
        /// </summary>
        public static string M_ExportSuccess {
            get {
                return ResourceManager.GetString("M_ExportSuccess", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 将替换现有非凭据数据、设置、名单、历史、资源、插件和插件私有配置。确认后会先自动创建完整恢复快照；快照失败时不会导入。安全凭据不会导入。.
        /// </summary>
        public static string M_ImportAllDataContent {
            get {
                return ResourceManager.GetString("M_ImportAllDataContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入失败，未完成覆盖。.
        /// </summary>
        public static string M_ImportFailed {
            get {
                return ResourceManager.GetString("M_ImportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 将替换当前所有非凭据设置，包括窗口、启动、主题、抽取和系统集成。确认后会先自动创建设置恢复快照；快照失败时不会导入。密码、TOTP、USB 绑定和锁定状态不会导入。.
        /// </summary>
        public static string M_ImportSettingsContent {
            get {
                return ResourceManager.GetString("M_ImportSettingsContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导入完成，恢复备份：{0}.
        /// </summary>
        public static string M_ImportSuccess {
            get {
                return ResourceManager.GetString("M_ImportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 确认导入.
        /// </summary>
        public static string M_ImportTitle {
            get {
                return ResourceManager.GetString("M_ImportTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 该文件不是受支持的 SecRandom v3 导出文件。.
        /// </summary>
        public static string M_ImportUnsupportedContent {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 不支持的导入文件.
        /// </summary>
        public static string M_ImportUnsupportedTitle {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 未识别.
        /// </summary>
        public static string M_ImportUnsupportedUnknownVersion {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedUnknownVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 检测到的导出版本：{0}\n\n{1}\n\n未创建恢复快照，也未修改任何数据。.
        /// </summary>
        public static string M_ImportUnsupportedVersion {
            get {
                return ResourceManager.GetString("M_ImportUnsupportedVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 需要重启.
        /// </summary>
        public static string M_NeedsRestarting {
            get {
                return ResourceManager.GetString("M_NeedsRestarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string M_NeedsRestarting_Close {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 部分设置需要重启以应用更改.
        /// </summary>
        public static string M_NeedsRestarting_D {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 重启.
        /// </summary>
        public static string M_NeedsRestarting_Primary {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Primary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 部分设置需要重启才能生效，点击以重启应用。.
        /// </summary>
        public static string M_NeedsRestarting_Tooltip {
            get {
                return ResourceManager.GetString("M_NeedsRestarting_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 导航时出现错误.
        /// </summary>
        public static string M_NavigateFailed {
            get {
                return ResourceManager.GetString("M_NavigateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法打开目录。.
        /// </summary>
        public static string M_OpenDirectoryFailed {
            get {
                return ResourceManager.GetString("M_OpenDirectoryFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 页面 {0} 未找到.
        /// </summary>
        public static string M_PageNotFound {
            get {
                return ResourceManager.GetString("M_PageNotFound", resourceCulture);
            }
        }

        public static string C_TransferFileExport => ResourceManager.GetString("C_TransferFileExport", resourceCulture);
        public static string C_TransferFileImport => ResourceManager.GetString("C_TransferFileImport", resourceCulture);
        public static string C_TransferQuickQrExport => ResourceManager.GetString("C_TransferQuickQrExport", resourceCulture);
        public static string C_TransferOfflineQrExport => ResourceManager.GetString("C_TransferOfflineQrExport", resourceCulture);
        public static string C_TransferSessionCodeExport => ResourceManager.GetString("C_TransferSessionCodeExport", resourceCulture);
        public static string C_TransferQuickQrImport => ResourceManager.GetString("C_TransferQuickQrImport", resourceCulture);
        public static string C_TransferOfflineQrImport => ResourceManager.GetString("C_TransferOfflineQrImport", resourceCulture);
        public static string C_TransferSessionCodeImport => ResourceManager.GetString("C_TransferSessionCodeImport", resourceCulture);
    }
}
