//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Feat_Settings {
            get {
                return ResourceManager.GetString("Feat_Settings", resourceCulture);
            }
        }
        
        public static string Menu_ToggleMainWindow {
            get {
                return ResourceManager.GetString("Menu_ToggleMainWindow", resourceCulture);
            }
        }
        
        public static string Menu_ToggleFloatingWindow {
            get {
                return ResourceManager.GetString("Menu_ToggleFloatingWindow", resourceCulture);
            }
        }
        
        public static string Menu_ShowMainWindow {
            get {
                return ResourceManager.GetString("Menu_ShowMainWindow", resourceCulture);
            }
        }
        
        public static string Menu_ShowFloatingWindow {
            get {
                return ResourceManager.GetString("Menu_ShowFloatingWindow", resourceCulture);
            }
        }
        
        public static string Menu_HideFloatingWindow {
            get {
                return ResourceManager.GetString("Menu_HideFloatingWindow", resourceCulture);
            }
        }
        
        public static string Feat_RollCall {
            get {
                return ResourceManager.GetString("Feat_RollCall", resourceCulture);
            }
        }
        
        public static string Feat_QuickDraw {
            get {
                return ResourceManager.GetString("Feat_QuickDraw", resourceCulture);
            }
        }
        
        public static string C_QuickDrawAutoCloseHint {
            get {
                return ResourceManager.GetString("C_QuickDrawAutoCloseHint", resourceCulture);
            }
        }
        
        public static string C_QuickDrawManualCloseHint {
            get {
                return ResourceManager.GetString("C_QuickDrawManualCloseHint", resourceCulture);
            }
        }
        
        public static string Feat_Lottery {
            get {
                return ResourceManager.GetString("Feat_Lottery", resourceCulture);
            }
        }

        public static string Feat_Timer {
            get {
                return ResourceManager.GetString("Feat_Timer", resourceCulture);
            }
        }
        
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        public static string Settings_Basic {
            get {
                return ResourceManager.GetString("Settings_Basic", resourceCulture);
            }
        }
        
        public static string Settings_RosterManagement {
            get {
                return ResourceManager.GetString("Settings_RosterManagement", resourceCulture);
            }
        }
        
        public static string Settings_Draw {
            get {
                return ResourceManager.GetString("Settings_Draw", resourceCulture);
            }
        }
        
        public static string Settings_FloatingWindow {
            get {
                return ResourceManager.GetString("Settings_FloatingWindow", resourceCulture);
            }
        }
        
        public static string Settings_Notification {
            get {
                return ResourceManager.GetString("Settings_Notification", resourceCulture);
            }
        }
        
        public static string Settings_RollCallNotification {
            get {
                return ResourceManager.GetString("Settings_RollCallNotification", resourceCulture);
            }
        }
        
        public static string Settings_QuickDrawNotification {
            get {
                return ResourceManager.GetString("Settings_QuickDrawNotification", resourceCulture);
            }
        }
        
        public static string Settings_LotteryNotification {
            get {
                return ResourceManager.GetString("Settings_LotteryNotification", resourceCulture);
            }
        }
        
        public static string Settings_Security {
            get {
                return ResourceManager.GetString("Settings_Security", resourceCulture);
            }
        }
        
        public static string Settings_Linkage {
            get {
                return ResourceManager.GetString("Settings_Linkage", resourceCulture);
            }
        }
        
        public static string Settings_Voice {
            get {
                return ResourceManager.GetString("Settings_Voice", resourceCulture);
            }
        }
        
        public static string Feat_History {
            get {
                return ResourceManager.GetString("Feat_History", resourceCulture);
            }
        }
        
        public static string Feat_RollCallHistory {
            get {
                return ResourceManager.GetString("Feat_RollCallHistory", resourceCulture);
            }
        }
        
        public static string Feat_LotteryHistory {
            get {
                return ResourceManager.GetString("Feat_LotteryHistory", resourceCulture);
            }
        }
        
        public static string Settings_HistoryManagement {
            get {
                return ResourceManager.GetString("Settings_HistoryManagement", resourceCulture);
            }
        }
        
        public static string Menu_OpenSettings {
            get {
                return ResourceManager.GetString("Menu_OpenSettings", resourceCulture);
            }
        }
        
        public static string Menu_OpenMainWindow {
            get {
                return ResourceManager.GetString("Menu_OpenMainWindow", resourceCulture);
            }
        }
        
        public static string Menu_ExitProgram {
            get {
                return ResourceManager.GetString("Menu_ExitProgram", resourceCulture);
            }
        }
        
        public static string App_Description {
            get {
                return ResourceManager.GetString("App_Description", resourceCulture);
            }
        }
        
        public static string App_License {
            get {
                return ResourceManager.GetString("App_License", resourceCulture);
            }
        }
        
        public static string C_ToBeWritten {
            get {
                return ResourceManager.GetString("C_ToBeWritten", resourceCulture);
            }
        }
        
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }
        
        public static string M_PortableDataDirectoryUnavailableTitle {
            get {
                return ResourceManager.GetString("M_PortableDataDirectoryUnavailableTitle", resourceCulture);
            }
        }
        
        public static string M_PortableDataDirectoryUnavailableContent {
            get {
                return ResourceManager.GetString("M_PortableDataDirectoryUnavailableContent", resourceCulture);
            }
        }
        
        public static string M_UnknownError {
            get {
                return ResourceManager.GetString("M_UnknownError", resourceCulture);
            }
        }
        
        public static string AttachedSettings_BehindScene {
            get {
                return ResourceManager.GetString("AttachedSettings_BehindScene", resourceCulture);
            }
        }
        
        public static string Settings_Backup {
            get {
                return ResourceManager.GetString("Settings_Backup", resourceCulture);
            }
        }
        
        public static string Menu_RestartProgram {
            get {
                return ResourceManager.GetString("Menu_RestartProgram", resourceCulture);
            }
        }
        
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        public static string Settings_Home {
            get {
                return ResourceManager.GetString("Settings_Home", resourceCulture);
            }
        }
        
        public static string Settings_Personalized {
            get {
                return ResourceManager.GetString("Settings_Personalized", resourceCulture);
            }
        }
        
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        public static string Settings_FairPick {
            get {
                return ResourceManager.GetString("Settings_FairPick", resourceCulture);
            }
        }
        
        public static string Settings_VoiceMusic {
            get {
                return ResourceManager.GetString("Settings_VoiceMusic", resourceCulture);
            }
        }
        
        public static string Settings_DefaultNotification {
            get {
                return ResourceManager.GetString("Settings_DefaultNotification", resourceCulture);
            }
        }
        
        public static string Settings_Plugin {
            get {
                return ResourceManager.GetString("Settings_Plugin", resourceCulture);
            }
        }
        
        public static string Settings_EnableShortcut {
            get {
                return ResourceManager.GetString("Settings_EnableShortcut", resourceCulture);
            }
        }
        
        public static string Settings_EnableShortcut_D {
            get {
                return ResourceManager.GetString("Settings_EnableShortcut_D", resourceCulture);
            }
        }
        
        public static string Settings_OpenRollCallPageShortcut {
            get {
                return ResourceManager.GetString("Settings_OpenRollCallPageShortcut", resourceCulture);
            }
        }
        
        public static string Settings_OpenRollCallPageShortcut_D {
            get {
                return ResourceManager.GetString("Settings_OpenRollCallPageShortcut_D", resourceCulture);
            }
        }
        
        public static string Settings_QuickDrawShortcut {
            get {
                return ResourceManager.GetString("Settings_QuickDrawShortcut", resourceCulture);
            }
        }
        
        public static string Settings_QuickDrawShortcut_D {
            get {
                return ResourceManager.GetString("Settings_QuickDrawShortcut_D", resourceCulture);
            }
        }
        
        public static string Settings_OpenLotteryPageShortcut {
            get {
                return ResourceManager.GetString("Settings_OpenLotteryPageShortcut", resourceCulture);
            }
        }
        
        public static string Settings_OpenLotteryPageShortcut_D {
            get {
                return ResourceManager.GetString("Settings_OpenLotteryPageShortcut_D", resourceCulture);
            }
        }
        
        public static string Settings_ShortcutExampleRollCall {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleRollCall", resourceCulture);
            }
        }
        
        public static string Settings_ShortcutExampleQuickDraw {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleQuickDraw", resourceCulture);
            }
        }
        
        public static string Settings_ShortcutExampleLottery {
            get {
                return ResourceManager.GetString("Settings_ShortcutExampleLottery", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ByTotal {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTotal", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ByTotal_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTotal_D", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ByGroup {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGroup", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ByGender {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByGender", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ByTime {
            get {
                return ResourceManager.GetString("Settings_FairPick_ByTime", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_Weights {
            get {
                return ResourceManager.GetString("Settings_FairPick_Weights", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_Protection {
            get {
                return ResourceManager.GetString("Settings_FairPick_Protection", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_GapProtection {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapProtection", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_GapThreshold {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapThreshold", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_GapThreshold_D {
            get {
                return ResourceManager.GetString("Settings_FairPick_GapThreshold_D", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_Shield {
            get {
                return ResourceManager.GetString("Settings_FairPick_Shield", resourceCulture);
            }
        }
        
        public static string Settings_FairPick_ColdStart {
            get {
                return ResourceManager.GetString("Settings_FairPick_ColdStart", resourceCulture);
            }
        }
        
        public static string MultiInstance_Title {
            get {
                return ResourceManager.GetString("MultiInstance_Title", resourceCulture);
            }
        }
        
        public static string MultiInstance_Message {
            get {
                return ResourceManager.GetString("MultiInstance_Message", resourceCulture);
            }
        }
        
        public static string MultiInstance_OpenExisting {
            get {
                return ResourceManager.GetString("MultiInstance_OpenExisting", resourceCulture);
            }
        }
        
        public static string MultiInstance_Restart {
            get {
                return ResourceManager.GetString("MultiInstance_Restart", resourceCulture);
            }
        }
        
        public static string MultiInstance_Cancel {
            get {
                return ResourceManager.GetString("MultiInstance_Cancel", resourceCulture);
            }
        }
        
        public static string C_PickButtonText {
            get {
                return ResourceManager.GetString("C_PickButtonText", resourceCulture);
            }
        }
    }
}
