; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#ifndef MyAppName
#define MyAppName "UNrandom"
#endif
#ifndef MyAppVersion
#define MyAppVersion "APP_VERSION"
#endif
#define MyAppPublisher "李骏健"
#define MyAppExeName "UNrandom.Desktop.exe"
#define MyAppURL "https://secrandom.sectl.cn/"
#ifndef MyAppOutDir
#define MyAppOutDir "APP_OUTDIR"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{841EEEA5-9A56-4DF5-9E75-27EEA063EF1F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppSupportURL={#MyAppURL}
#ifdef UiAccessBuild
DefaultDirName={autopf}\SECTL\UNrandom
#else
DefaultDirName={localappdata}\SECTL\UNrandom
#endif
UninstallDisplayIcon={app}\{#MyAppExeName}
#ifdef BuildArchX86
ArchitecturesAllowed=x86compatible
#else
#ifdef BuildArchArm64
ArchitecturesAllowed=arm64
ArchitecturesInstallIn64BitMode=arm64
#else
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
#endif
#endif
DisableProgramGroupPage=yes
; LicenseFile=E:\Projects\Avalonia\SecRandom\LICENSE
#ifdef UiAccessBuild
; UIAccess is granted only to signed binaries installed under Program Files.
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=none
#else
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
#endif
OutputDir=artifacts\release\setup
OutputBaseFilename=SecRandom-Setup
SetupIconFile=SecRandom\Assets\AppLogo.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11
LanguageDetectionMethod=none

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MyAppOutDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#MyAppOutDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

