//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Personalized.Appearance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Personalized.Appearance.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体预览.
        /// </summary>
        public static string C_Font_Preview {
            get {
                return ResourceManager.GetString("C_Font_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 树梢树枝树根根 亲山亲水有亲人
        ///第一小组 张三 第二小组 李四 第三小组 王五 第四小组 赵六
        ///the quick brown fox jumps over a lazy dog
        ///THE QUICK BROWN FOX JUMPS OVER A LAZY DOG
        ///点名 闪抽 抽奖 1234567890 +-*/.
        /// </summary>
        public static string C_Font_Preview_Text {
            get {
                return ResourceManager.GetString("C_Font_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiSans (默认).
        /// </summary>
        public static string O_FontFamily_Default {
            get {
                return ResourceManager.GetString("O_FontFamily_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极粗.
        /// </summary>
        public static string O_FontWeight_Black {
            get {
                return ResourceManager.GetString("O_FontWeight_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粗体.
        /// </summary>
        public static string O_FontWeight_Bold {
            get {
                return ResourceManager.GetString("O_FontWeight_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特粗.
        /// </summary>
        public static string O_FontWeight_ExtraBold {
            get {
                return ResourceManager.GetString("O_FontWeight_ExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特细.
        /// </summary>
        public static string O_FontWeight_ExtraLight {
            get {
                return ResourceManager.GetString("O_FontWeight_ExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 细体.
        /// </summary>
        public static string O_FontWeight_Light {
            get {
                return ResourceManager.GetString("O_FontWeight_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中等.
        /// </summary>
        public static string O_FontWeight_Medium {
            get {
                return ResourceManager.GetString("O_FontWeight_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规.
        /// </summary>
        public static string O_FontWeight_Regular {
            get {
                return ResourceManager.GetString("O_FontWeight_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半粗.
        /// </summary>
        public static string O_FontWeight_SemiBold {
            get {
                return ResourceManager.GetString("O_FontWeight_SemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 极细.
        /// </summary>
        public static string O_FontWeight_Thin {
            get {
                return ResourceManager.GetString("O_FontWeight_Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string O_Theme_Auto {
            get {
                return ResourceManager.GetString("O_Theme_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深色.
        /// </summary>
        public static string O_Theme_Dark {
            get {
                return ResourceManager.GetString("O_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浅色.
        /// </summary>
        public static string O_Theme_Light {
            get {
                return ResourceManager.GetString("O_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        public static string O_ThemeColorMode_Custom {
            get {
                return ResourceManager.GetString("O_ThemeColorMode_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        public static string O_ThemeColorMode_System {
            get {
                return ResourceManager.GetString("O_ThemeColorMode_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体.
        /// </summary>
        public static string S_Font {
            get {
                return ResourceManager.GetString("S_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体家族.
        /// </summary>
        public static string S_Font_FontFamily {
            get {
                return ResourceManager.GetString("S_Font_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面显示字体家族.
        /// </summary>
        public static string S_Font_FontFamily_D {
            get {
                return ResourceManager.GetString("S_Font_FontFamily_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体粗细.
        /// </summary>
        public static string S_Font_FontWeight {
            get {
                return ResourceManager.GetString("S_Font_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面字体粗细.
        /// </summary>
        public static string S_Font_FontWeight_D {
            get {
                return ResourceManager.GetString("S_Font_FontWeight_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string S_Theme {
            get {
                return ResourceManager.GetString("S_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题模式.
        /// </summary>
        public static string S_Theme_Theme {
            get {
                return ResourceManager.GetString("S_Theme_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择软件界面主题样式.
        /// </summary>
        public static string S_Theme_Theme_D {
            get {
                return ResourceManager.GetString("S_Theme_Theme_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题颜色.
        /// </summary>
        public static string S_Theme_ThemeColor {
            get {
                return ResourceManager.GetString("S_Theme_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置软件界面主题色彩.
        /// </summary>
        public static string S_Theme_ThemeColor_D {
            get {
                return ResourceManager.GetString("S_Theme_ThemeColor_D", resourceCulture);
            }
        }
    }
}
