<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <GenerateResourceDesigner>true</GenerateResourceDesigner>
        <HotAvaloniaIncludeExtensions>True</HotAvaloniaIncludeExtensions>
        <!-- These views are created with DI/state constructors and load AXAML into an existing instance. -->
        <NoWarn>$(NoWarn);AVLN3001</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <HotAvaloniaAutoEnable>False</HotAvaloniaAutoEnable>
        <HotAvalonia Condition="'$(Configuration)' == 'Debug'">True</HotAvalonia>
        <SecRandomBundleAssetsInAssembly Condition="'$(SecRandomBundleAssetsInAssembly)' == ''">true</SecRandomBundleAssetsInAssembly>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" Condition="'$(SecRandomBundleAssetsInAssembly)' == 'true'" />
        <None Update="Assets\**" Condition="'$(SecRandomBundleAssetsInAssembly)' != 'true'">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
            <PublishFolderType>Resource</PublishFolderType>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SecRandom.Core\SecRandom.Core.csproj" />
        <ProjectReference Include="..\SecRandom.PluginSdk\SecRandom.PluginSdk.csproj" />
        <ProjectReference Include="..\SecRandom4Ci.Interface\SecRandom4Ci.Interface.csproj" />
        <ProjectReference Include="..\SecRandom.Platforms\SecRandom.Platforms.csproj" />
        <ProjectReference Include="..\SecRandom.Platforms.Abstractions\SecRandom.Platforms.Abstractions.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Update="Langs\Common\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\CrashRecovery\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\FirstRunOobe\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\MainPages\RollCall\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\MainPages\QuickDraw\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\MainPages\Timer\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\MainPages\Lottery\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\MainPages\History\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsView\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\General\Basic\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\General\Privacy\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\General\Verification\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\General\Backup\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Announcements\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Personalized\Appearance\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Personalized\Music\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\About\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Debug\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Plugins\Overview\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\AttachedSettings\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\ListManagement\RollCallList\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\ListManagement\LotteryList\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Picking\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\FloatingWindow\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Notification\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Security\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\Ipc\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Linkage\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Voice\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\HistoryManagement\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Update\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\LogViewer\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\More\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\SettingsPages\Home\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>

        <EmbeddedResource Update="Langs\Mobile\Resources.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Langs\Common\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\CrashRecovery\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\FirstRunOobe\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\MainPages\RollCall\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\MainPages\QuickDraw\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\MainPages\Lottery\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsView\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\General\Basic\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\General\Privacy\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\General\Verification\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\General\Backup\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Announcements\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Personalized\Appearance\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Personalized\Music\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\About\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Debug\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Plugins\Overview\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\AttachedSettings\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\ListManagement\RollCallList\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\ListManagement\LotteryList\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Picking\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\FloatingWindow\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Notification\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Security\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\Ipc\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Linkage\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Voice\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\HistoryManagement\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Update\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\LogViewer\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\More\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\SettingsPages\Home\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Langs\Mobile\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\DefaultNotificationSettingsPage.axaml.cs">
          <DependentUpon>DefaultNotificationSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\LotteryNotificationSettingsPage.axaml.cs">
          <DependentUpon>LotteryNotificationSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\NotificationChannelSettingsContent.axaml.cs">
          <DependentUpon>NotificationChannelSettingsContent.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\RollCallNotificationSettingsPage.axaml.cs">
          <DependentUpon>RollCallNotificationSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\VoiceSettingsPage.axaml.cs">
          <DependentUpon>VoiceSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Notification\QuickDrawNotificationSettingsPage.axaml.cs">
          <DependentUpon>QuickDrawNotificationSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>


        <Compile Update="Views\SettingsPages\General\SecuritySettingsPage.axaml.cs">
          <DependentUpon>SecuritySettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Personalized\FloatingWindowSettingsPage.axaml.cs">
          <DependentUpon>FloatingWindowSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>

        <Compile Update="Views\SettingsPages\Personalized\MusicSettingsPage.axaml.cs">
          <DependentUpon>MusicSettingsPage.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaloniaVersion)" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="HotAvalonia" Version="3.1.4" />
        <PackageReference Include="HotAvalonia.Core" Version="3.1.4" />
        <PackageReference Include="QRCoder" Version="1.8.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
        <PackageReference Include="CameraView.Avalonia" Version="1.0.18" />
        <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
        <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
        <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.13.0.20260627" />
        <PackageReference Include="OpenCvSharp4.runtime.osx.10.15-x64" Version="4.6.0.20230105"
                          Condition="'$(RuntimeIdentifier)' == 'osx-x64'" />
        <PackageReference Include="OpenCvSharp4.runtime.osx_arm64" Version="4.8.1-rc"
                          Condition="'$(RuntimeIdentifier)' == 'osx-arm64'" />
        <PackageReference Include="SoundFlow" Version="[1.2.1.3]" />
        <PackageReference Include="ClassIsland.Shared.IPC" Version="2.1.0.1" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
        <PackageReference Include="YamlDotNet" Version="18.1.0" />
        <PackageReference Include="ZXing.Net" Version="0.16.9" />
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Edge_tts.cs" Link="ThirdParty\EdgeTtsSharp\Edge_tts.cs" />
        <Compile Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Tools.cs" Link="ThirdParty\EdgeTtsSharp\Tools.cs" />
        <Compile Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Model\eVoice.cs" Link="ThirdParty\EdgeTtsSharp\Model\eVoice.cs" />
        <Compile Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Model\PlayOption.cs" Link="ThirdParty\EdgeTtsSharp\Model\PlayOption.cs" />
        <Compile Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Model\Log.cs" Link="ThirdParty\EdgeTtsSharp\Model\Log.cs" />
        <EmbeddedResource Include="..\vendors\EdgeTtsSharp\Edge_tts_sharp\Source\VoiceList.json" Link="ThirdParty\EdgeTtsSharp\Source\VoiceList.json" LogicalName="Edge_tts_sharp.Source.VoiceList.json" />
    </ItemGroup>

    <Import Project="..\Global.props" />
</Project>
