//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.CrashRecovery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.CrashRecovery.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 已复制.
        /// </summary>
        public static string C_CopyDone {
            get {
                return ResourceManager.GetString("C_CopyDone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 复制失败.
        /// </summary>
        public static string C_CopyFailed {
            get {
                return ResourceManager.GetString("C_CopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 复制报告.
        /// </summary>
        public static string C_CopyReport {
            get {
                return ResourceManager.GetString("C_CopyReport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 忽略.
        /// </summary>
        public static string C_Ignore {
            get {
                return ResourceManager.GetString("C_Ignore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 打开失败.
        /// </summary>
        public static string C_ReportFailed {
            get {
                return ResourceManager.GetString("C_ReportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string C_ReportGitHub {
            get {
                return ResourceManager.GetString("C_ReportGitHub", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 反馈问题.
        /// </summary>
        public static string C_ReportIssue {
            get {
                return ResourceManager.GetString("C_ReportIssue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 重新启动.
        /// </summary>
        public static string C_Restart {
            get {
                return ResourceManager.GetString("C_Restart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} 秒后重启.
        /// </summary>
        public static string C_RestartCountdown {
            get {
                return ResourceManager.GetString("C_RestartCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 遇到了未处理的错误。下面是本次崩溃报告，可复制后反馈问题，或重新启动程序。.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用发生未处理异常并进入崩溃恢复。.
        /// </summary>
        public static string FeedbackActual {
            get {
                return ResourceManager.GetString("FeedbackActual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ## 崩溃报告
        ///
        ///```text
        ///{0}
        ///```.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用应稳定运行，不应发生未处理异常。.
        /// </summary>
        public static string FeedbackExpected {
            get {
                return ResourceManager.GetString("FeedbackExpected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 崩溃报告已自动收集，请参考随附诊断信息。.
        /// </summary>
        public static string FeedbackReproduction {
            get {
                return ResourceManager.GetString("FeedbackReproduction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 崩溃报告.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 无堆栈信息.
        /// </summary>
        public static string NoStackTrace {
            get {
                return ResourceManager.GetString("NoStackTrace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 无法读取崩溃报告：{0}.
        /// </summary>
        public static string ReportUnavailable {
            get {
                return ResourceManager.GetString("ReportUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 崩溃恢复.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
