//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.Picking {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.Picking.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 淡入.
        /// </summary>
        public static string C_FadeIn {
            get {
                return ResourceManager.GetString("C_FadeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 淡出.
        /// </summary>
        public static string C_FadeOut {
            get {
                return ResourceManager.GetString("C_FadeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 直接轮换.
        /// </summary>
        public static string O_AnimationDirectRotate {
            get {
                return ResourceManager.GetString("O_AnimationDirectRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 淡入上浮.
        /// </summary>
        public static string O_AnimationFadeFloat {
            get {
                return ResourceManager.GetString("O_AnimationFadeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左右晃动.
        /// </summary>
        public static string O_AnimationHorizontalShake {
            get {
                return ResourceManager.GetString("O_AnimationHorizontalShake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动播放.
        /// </summary>
        public static string O_AutoPlay {
            get {
                return ResourceManager.GetString("O_AutoPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号和姓名.
        /// </summary>
        public static string O_Both {
            get {
                return ResourceManager.GetString("O_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下方.
        /// </summary>
        public static string O_Bottom {
            get {
                return ResourceManager.GetString("O_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡片.
        /// </summary>
        public static string O_Card {
            get {
                return ResourceManager.GetString("O_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动清除.
        /// </summary>
        public static string O_Cleared {
            get {
                return ResourceManager.GetString("O_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按剩余数量.
        /// </summary>
        public static string O_Count {
            get {
                return ResourceManager.GetString("O_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        public static string O_Custom {
            get {
                return ResourceManager.GetString("O_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认.
        /// </summary>
        public static string O_Default {
            get {
                return ResourceManager.GetString("O_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公平抽取.
        /// </summary>
        public static string O_Fair {
            get {
                return ResourceManager.GetString("O_Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定颜色.
        /// </summary>
        public static string O_FixedColor {
            get {
                return ResourceManager.GetString("O_FixedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随全局.
        /// </summary>
        public static string O_FollowGlobal {
            get {
                return ResourceManager.GetString("O_FollowGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半重复.
        /// </summary>
        public static string O_HalfRepeat {
            get {
                return ResourceManager.GetString("O_HalfRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅编号.
        /// </summary>
        public static string O_Id {
            get {
                return ResourceManager.GetString("O_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左侧.
        /// </summary>
        public static string O_Left {
            get {
                return ResourceManager.GetString("O_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动停止.
        /// </summary>
        public static string O_ManualStop {
            get {
                return ResourceManager.GetString("O_ManualStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部文件：{0}.
        /// </summary>
        public static string O_MusicExternal {
            get {
                return ResourceManager.GetString("O_MusicExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可用：{0}.
        /// </summary>
        public static string O_MusicUnavailable {
            get {
                return ResourceManager.GetString("O_MusicUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅姓名.
        /// </summary>
        public static string O_Name {
            get {
                return ResourceManager.GetString("O_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无动画.
        /// </summary>
        public static string O_NoAnimation {
            get {
                return ResourceManager.GetString("O_NoAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        public static string O_NoColor {
            get {
                return ResourceManager.GetString("O_NoColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不开启音乐.
        /// </summary>
        public static string O_NoMusic {
            get {
                return ResourceManager.GetString("O_NoMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不重复.
        /// </summary>
        public static string O_NoRepeat {
            get {
                return ResourceManager.GetString("O_NoRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按奖盘.
        /// </summary>
        public static string O_Pan {
            get {
                return ResourceManager.GetString("O_Pan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品/小组.
        /// </summary>
        public static string O_PrizeBreakGroup {
            get {
                return ResourceManager.GetString("O_PrizeBreakGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品/小组/姓名.
        /// </summary>
        public static string O_PrizeBreakGroupBreakName {
            get {
                return ResourceManager.GetString("O_PrizeBreakGroupBreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品/小组-姓名.
        /// </summary>
        public static string O_PrizeBreakGroupHyphenName {
            get {
                return ResourceManager.GetString("O_PrizeBreakGroupHyphenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品/姓名.
        /// </summary>
        public static string O_PrizeBreakName {
            get {
                return ResourceManager.GetString("O_PrizeBreakName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品-小组.
        /// </summary>
        public static string O_PrizeHyphenGroup {
            get {
                return ResourceManager.GetString("O_PrizeHyphenGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品-小组-姓名.
        /// </summary>
        public static string O_PrizeHyphenGroupHyphenName {
            get {
                return ResourceManager.GetString("O_PrizeHyphenGroupHyphenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品-姓名.
        /// </summary>
        public static string O_PrizeHyphenName {
            get {
                return ResourceManager.GetString("O_PrizeHyphenName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 序号 奖品/分组-名称.
        /// </summary>
        public static string O_PrizeIdPrizeBreakGroupHyphenMember {
            get {
                return ResourceManager.GetString("O_PrizeIdPrizeBreakGroupHyphenMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机抽取.
        /// </summary>
        public static string O_Random {
            get {
                return ResourceManager.GetString("O_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机.
        /// </summary>
        public static string O_RandomColor {
            get {
                return ResourceManager.GetString("O_RandomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随机播放.
        /// </summary>
        public static string O_RandomMusic {
            get {
                return ResourceManager.GetString("O_RandomMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许重复.
        /// </summary>
        public static string O_Repeat {
            get {
                return ResourceManager.GetString("O_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启后清除.
        /// </summary>
        public static string O_Restarted {
            get {
                return ResourceManager.GetString("O_Restarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右侧.
        /// </summary>
        public static string O_Right {
            get {
                return ResourceManager.GetString("O_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上方.
        /// </summary>
        public static string O_Top {
            get {
                return ResourceManager.GetString("O_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖抽取设置.
        /// </summary>
        public static string Page_Lottery {
            get {
                return ResourceManager.GetString("Page_Lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画模式.
        /// </summary>
        public static string S_Animation {
            get {
                return ResourceManager.GetString("S_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取动画播放方式.
        /// </summary>
        public static string S_Animation_D {
            get {
                return ResourceManager.GetString("S_Animation_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画间隔.
        /// </summary>
        public static string S_AnimationInterval {
            get {
                return ResourceManager.GetString("S_AnimationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取动画每次切换的间隔（毫秒）.
        /// </summary>
        public static string S_AnimationInterval_D {
            get {
                return ResourceManager.GetString("S_AnimationInterval_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画音乐.
        /// </summary>
        public static string S_AnimationMusic {
            get {
                return ResourceManager.GetString("S_AnimationMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择抽取动画播放时使用的音乐。.
        /// </summary>
        public static string S_AnimationMusic_D {
            get {
                return ResourceManager.GetString("S_AnimationMusic_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 循环播放动画音乐.
        /// </summary>
        public static string S_AnimationMusicLoop {
            get {
                return ResourceManager.GetString("S_AnimationMusicLoop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 动画持续期间重复播放动画音乐。.
        /// </summary>
        public static string S_AnimationMusicLoop_D {
            get {
                return ResourceManager.GetString("S_AnimationMusicLoop_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画音乐淡入和淡出.
        /// </summary>
        public static string S_AnimationMusicFade {
            get {
                return ResourceManager.GetString("S_AnimationMusicFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上方滑块控制淡入，下方滑块控制淡出，单位为毫秒。.
        /// </summary>
        public static string S_AnimationMusicFade_D {
            get {
                return ResourceManager.GetString("S_AnimationMusicFade_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画音乐音量.
        /// </summary>
        public static string S_AnimationMusicVolume {
            get {
                return ResourceManager.GetString("S_AnimationMusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取动画音乐的音量。.
        /// </summary>
        public static string S_AnimationMusicVolume_D {
            get {
                return ResourceManager.GetString("S_AnimationMusicVolume_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画样式.
        /// </summary>
        public static string S_AnimationStyle {
            get {
                return ResourceManager.GetString("S_AnimationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取过程和最终定格时使用的统一动画效果.
        /// </summary>
        public static string S_AnimationStyle_D {
            get {
                return ResourceManager.GetString("S_AnimationStyle_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动播放次数.
        /// </summary>
        public static string S_AutoplayCount {
            get {
                return ResourceManager.GetString("S_AutoplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动播放模式下滚动候选结果的次数.
        /// </summary>
        public static string S_AutoplayCount_D {
            get {
                return ResourceManager.GetString("S_AutoplayCount_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除记录.
        /// </summary>
        public static string S_ClearRecord {
            get {
                return ResourceManager.GetString("S_ClearRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制抽取记录何时清除.
        /// </summary>
        public static string S_ClearRecord_D {
            get {
                return ResourceManager.GetString("S_ClearRecord_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题.
        /// </summary>
        public static string S_ColorTheme {
            get {
                return ResourceManager.GetString("S_ColorTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取动画和结果颜色来源.
        /// </summary>
        public static string S_ColorTheme_D {
            get {
                return ResourceManager.GetString("S_ColorTheme_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义字体.
        /// </summary>
        public static string S_CustomFont {
            get {
                return ResourceManager.GetString("S_CustomFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体族名称，留空时使用默认字体.
        /// </summary>
        public static string S_CustomFont_D {
            get {
                return ResourceManager.GetString("S_CustomFont_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认抽取名单.
        /// </summary>
        public static string S_DefaultClass {
            get {
                return ResourceManager.GetString("S_DefaultClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开页面或执行闪抽时默认使用的名单.
        /// </summary>
        public static string S_DefaultClass_D {
            get {
                return ResourceManager.GetString("S_DefaultClass_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 默认抽奖名单.
        /// </summary>
        public static string S_DefaultPool {
            get {
                return ResourceManager.GetString("S_DefaultPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开抽奖页时默认使用的奖池.
        /// </summary>
        public static string S_DefaultPool_D {
            get {
                return ResourceManager.GetString("S_DefaultPool_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击后禁用时间.
        /// </summary>
        public static string S_DisableAfterClick {
            get {
                return ResourceManager.GetString("S_DisableAfterClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击一次闪抽后禁用按钮的秒数.
        /// </summary>
        public static string S_DisableAfterClick_D {
            get {
                return ResourceManager.GetString("S_DisableAfterClick_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示格式.
        /// </summary>
        public static string S_DisplayFormat {
            get {
                return ResourceManager.GetString("S_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制结果中显示姓名、编号或两者.
        /// </summary>
        public static string S_DisplayFormat_D {
            get {
                return ResourceManager.GetString("S_DisplayFormat_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示样式.
        /// </summary>
        public static string S_DisplayStyle {
            get {
                return ResourceManager.GetString("S_DisplayStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制抽取结果的整体样式.
        /// </summary>
        public static string S_DisplayStyle_D {
            get {
                return ResourceManager.GetString("S_DisplayStyle_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取模式.
        /// </summary>
        public static string S_DrawMode {
            get {
                return ResourceManager.GetString("S_DrawMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制重复抽取记录的处理方式.
        /// </summary>
        public static string S_DrawMode_D {
            get {
                return ResourceManager.GetString("S_DrawMode_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取方式.
        /// </summary>
        public static string S_DrawType {
            get {
                return ResourceManager.GetString("S_DrawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置使用随机抽取或公平抽取.
        /// </summary>
        public static string S_DrawType_D {
            get {
                return ResourceManager.GetString("S_DrawType_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定颜色.
        /// </summary>
        public static string S_FixedColor {
            get {
                return ResourceManager.GetString("S_FixedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色主题为固定颜色时使用.
        /// </summary>
        public static string S_FixedColor_D {
            get {
                return ResourceManager.GetString("S_FixedColor_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体大小.
        /// </summary>
        public static string S_FontSize {
            get {
                return ResourceManager.GetString("S_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取结果文字大小.
        /// </summary>
        public static string S_FontSize_D {
            get {
                return ResourceManager.GetString("S_FontSize_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体来源.
        /// </summary>
        public static string S_FontSource {
            get {
                return ResourceManager.GetString("S_FontSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随全局字体或为抽取结果单独指定字体.
        /// </summary>
        public static string S_FontSource_D {
            get {
                return ResourceManager.GetString("S_FontSource_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 半重复阈值.
        /// </summary>
        public static string S_HalfRepeat {
            get {
                return ResourceManager.GetString("S_HalfRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽中次数达到该值后不会再次进入候选池.
        /// </summary>
        public static string S_HalfRepeat_D {
            get {
                return ResourceManager.GetString("S_HalfRepeat_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖方式.
        /// </summary>
        public static string S_LotteryDrawType {
            get {
                return ResourceManager.GetString("S_LotteryDrawType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置按奖盘或按剩余数量抽奖.
        /// </summary>
        public static string S_LotteryDrawType_D {
            get {
                return ResourceManager.GetString("S_LotteryDrawType_D", resourceCulture);
            }
        }

        public static string S_LotteryAlgorithm => ResourceManager.GetString("S_LotteryAlgorithm", resourceCulture);
        public static string S_LotteryAlgorithm_D => ResourceManager.GetString("S_LotteryAlgorithm_D", resourceCulture);
        public static string S_RollCallAlgorithm => ResourceManager.GetString("S_RollCallAlgorithm", resourceCulture);
        public static string S_RollCallAlgorithm_D => ResourceManager.GetString("S_RollCallAlgorithm_D", resourceCulture);
        public static string O_AlgorithmFair => ResourceManager.GetString("O_AlgorithmFair", resourceCulture);
        public static string O_AlgorithmRandom => ResourceManager.GetString("O_AlgorithmRandom", resourceCulture);
        public static string O_AlgorithmInventory => ResourceManager.GetString("O_AlgorithmInventory", resourceCulture);
        public static string O_AlgorithmWeighted => ResourceManager.GetString("O_AlgorithmWeighted", resourceCulture);
        
        /// <summary>
        ///   Looks up a localized string similar to 显示奖品图片.
        /// </summary>
        public static string S_LotteryImage {
            get {
                return ResourceManager.GetString("S_LotteryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在抽奖结果中显示奖品图片。.
        /// </summary>
        public static string S_LotteryImage_D {
            get {
                return ResourceManager.GetString("S_LotteryImage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片位置.
        /// </summary>
        public static string S_LotteryImagePosition {
            get {
                return ResourceManager.GetString("S_LotteryImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片相对文字的位置。.
        /// </summary>
        public static string S_LotteryImagePosition_D {
            get {
                return ResourceManager.GetString("S_LotteryImagePosition_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量设置头像.
        /// </summary>
        public static string C_BatchAvatar {
            get {
                return ResourceManager.GetString("C_BatchAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择目录.
        /// </summary>
        public static string C_BatchAvatarChooseDirectory {
            get {
                return ResourceManager.GetString("C_BatchAvatarChooseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新选择外部文件.
        /// </summary>
        public static string C_BatchAvatarChooseFile {
            get {
                return ResourceManager.GetString("C_BatchAvatarChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片只从所选目录的第一层查找.
        /// </summary>
        public static string C_BatchAvatarDirectoryHint {
            get {
                return ResourceManager.GetString("C_BatchAvatarDirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像文件.
        /// </summary>
        public static string C_BatchAvatarFile {
            get {
                return ResourceManager.GetString("C_BatchAvatarFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据记录的名称或编号，从所选目录的第一层图片中批量匹配并设置头像.
        /// </summary>
        public static string C_BatchAvatarHint {
            get {
                return ResourceManager.GetString("C_BatchAvatarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动匹配 {0} 条记录.
        /// </summary>
        public static string C_BatchAvatarMatchSummary {
            get {
                return ResourceManager.GetString("C_BatchAvatarMatchSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未选择目录.
        /// </summary>
        public static string C_BatchAvatarNoDirectorySelected {
            get {
                return ResourceManager.GetString("C_BatchAvatarNoDirectorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖名单.
        /// </summary>
        public static string C_BatchAvatarPrize {
            get {
                return ResourceManager.GetString("C_BatchAvatarPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录.
        /// </summary>
        public static string C_BatchAvatarRecord {
            get {
                return ResourceManager.GetString("C_BatchAvatarRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点名名单.
        /// </summary>
        public static string C_BatchAvatarRoster {
            get {
                return ResourceManager.GetString("C_BatchAvatarRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定点名名单.
        /// </summary>
        public static string C_BatchAvatarTargetRoster {
            get {
                return ResourceManager.GetString("C_BatchAvatarTargetRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定抽奖名单.
        /// </summary>
        public static string C_BatchAvatarTargetPrize {
            get {
                return ResourceManager.GetString("C_BatchAvatarTargetPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string C_BatchAvatarSet {
            get {
                return ResourceManager.GetString("C_BatchAvatarSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string C_Confirm {
            get {
                return ResourceManager.GetString("C_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置点名名单头像.
        /// </summary>
        public static string C_SetAvatarViaRoster {
            get {
                return ResourceManager.GetString("C_SetAvatarViaRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前往点名名单页面，用成员附加设置「展示图片」设置头像.
        /// </summary>
        public static string C_SetAvatarViaRoster_D {
            get {
                return ResourceManager.GetString("C_SetAvatarViaRoster_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽奖名单头像.
        /// </summary>
        public static string C_SetAvatarViaPrize {
            get {
                return ResourceManager.GetString("C_SetAvatarViaPrize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前往抽奖名单页面，用奖品附加设置「展示图片」设置奖品图片.
        /// </summary>
        public static string C_SetAvatarViaPrize_D {
            get {
                return ResourceManager.GetString("C_SetAvatarViaPrize_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已为 {0} 条记录设置头像.
        /// </summary>
        public static string M_BatchAvatarApplied {
            get {
                return ResourceManager.GetString("M_BatchAvatarApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到头像文件：{0}.
        /// </summary>
        public static string M_BatchAvatarFileNotFound {
            get {
                return ResourceManager.GetString("M_BatchAvatarFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先选择包含图片的目录.
        /// </summary>
        public static string M_BatchAvatarNoDirectory {
            get {
                return ResourceManager.GetString("M_BatchAvatarNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖过程显示.
        /// </summary>
        public static string S_LotteryShowRandom {
            get {
                return ResourceManager.GetString("S_LotteryShowRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽奖过程中候选结果的展示格式.
        /// </summary>
        public static string S_LotteryShowRandom_D {
            get {
                return ResourceManager.GetString("S_LotteryShowRandom_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 自定义显示格式.
        /// </summary>
        public static string S_LotteryShowRandomFormat {
            get {
                return ResourceManager.GetString("S_LotteryShowRandomFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 设置抽奖过程的自定义展示格式.
        /// </summary>
        public static string S_LotteryShowRandomFormat_D {
            get {
                return ResourceManager.GetString("S_LotteryShowRandomFormat_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 插入格式变量.
        /// </summary>
        public static string C_LotteryShowRandomFormatTokens {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatTokens", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 支持使用以下格式化变量，点按变量即可插入：.
        /// </summary>
        public static string C_LotteryShowRandomFormatIntro {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string C_LotteryShowRandomFormatId {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 奖项.
        /// </summary>
        public static string C_LotteryShowRandomFormatPrize {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatPrize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 奖项 ID.
        /// </summary>
        public static string C_LotteryShowRandomFormatPrizeId {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatPrizeId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 奖项名称.
        /// </summary>
        public static string C_LotteryShowRandomFormatPrizeName {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatPrizeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 成员.
        /// </summary>
        public static string C_LotteryShowRandomFormatMember {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 成员 ID.
        /// </summary>
        public static string C_LotteryShowRandomFormatMemberId {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatMemberId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 成员名字.
        /// </summary>
        public static string C_LotteryShowRandomFormatMemberName {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatMemberName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 成员分组.
        /// </summary>
        public static string C_LotteryShowRandomFormatGroup {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 格式.
        /// </summary>
        public static string C_LotteryShowRandomFormatFormat {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 换行.
        /// </summary>
        public static string C_LotteryShowRandomFormatLineBreak {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatLineBreak", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 除换行符以外，其他分隔符可直接输入.
        /// </summary>
        public static string C_LotteryShowRandomFormatDirectSeparators {
            get {
                return ResourceManager.GetString("C_LotteryShowRandomFormatDirectSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐淡入淡出.
        /// </summary>
        public static string S_MusicFadeInOut {
            get {
                return ResourceManager.GetString("S_MusicFadeInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依次设置动画音乐淡入、动画音乐淡出、结果音乐淡入和结果音乐淡出时间（毫秒）。.
        /// </summary>
        public static string S_MusicFadeInOut_D {
            get {
                return ResourceManager.GetString("S_MusicFadeInOut_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐音量.
        /// </summary>
        public static string S_MusicVolume {
            get {
                return ResourceManager.GetString("S_MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 依次设置动画音乐和结果音乐的音量。.
        /// </summary>
        public static string S_MusicVolume_D {
            get {
                return ResourceManager.GetString("S_MusicVolume_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语字体大小.
        /// </summary>
        public static string S_ReminderFontSize {
            get {
                return ResourceManager.GetString("S_ReminderFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语文字大小.
        /// </summary>
        public static string S_ReminderFontSize_D {
            get {
                return ResourceManager.GetString("S_ReminderFontSize_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语.
        /// </summary>
        public static string S_ReminderText {
            get {
                return ResourceManager.GetString("S_ReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取页结果区域旁显示的提示文字.
        /// </summary>
        public static string S_ReminderText_D {
            get {
                return ResourceManager.GetString("S_ReminderText_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语颜色.
        /// </summary>
        public static string S_ReminderTextColor {
            get {
                return ResourceManager.GetString("S_ReminderTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语文字颜色.
        /// </summary>
        public static string S_ReminderTextColor_D {
            get {
                return ResourceManager.GetString("S_ReminderTextColor_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语透明度.
        /// </summary>
        public static string S_ReminderTextOpacity {
            get {
                return ResourceManager.GetString("S_ReminderTextOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语文字透明度（0-100）.
        /// </summary>
        public static string S_ReminderTextOpacity_D {
            get {
                return ResourceManager.GetString("S_ReminderTextOpacity_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果音乐.
        /// </summary>
        public static string S_ResultMusic {
            get {
                return ResourceManager.GetString("S_ResultMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择抽取结果出现时使用的音乐。.
        /// </summary>
        public static string S_ResultMusic_D {
            get {
                return ResourceManager.GetString("S_ResultMusic_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果音乐淡入和淡出.
        /// </summary>
        public static string S_ResultMusicFade {
            get {
                return ResourceManager.GetString("S_ResultMusicFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上方滑块控制淡入，下方滑块控制淡出，单位为毫秒。.
        /// </summary>
        public static string S_ResultMusicFade_D {
            get {
                return ResourceManager.GetString("S_ResultMusicFade_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果音乐音量.
        /// </summary>
        public static string S_ResultMusicVolume {
            get {
                return ResourceManager.GetString("S_ResultMusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置抽取结果音乐的音量。.
        /// </summary>
        public static string S_ResultMusicVolume_D {
            get {
                return ResourceManager.GetString("S_ResultMusicVolume_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示标签.
        /// </summary>
        public static string S_ShowTags {
            get {
                return ResourceManager.GetString("S_ShowTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取结果中展示学生或奖品标签.
        /// </summary>
        public static string S_ShowTags_D {
            get {
                return ResourceManager.GetString("S_ShowTags_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权重透明化.
        /// </summary>
        public static string S_ShowWeightTransparency {
            get {
                return ResourceManager.GetString("S_ShowWeightTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在结果展示中显示权重透明信息.
        /// </summary>
        public static string S_ShowWeightTransparency_D {
            get {
                return ResourceManager.GetString("S_ShowWeightTransparency_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示头像.
        /// </summary>
        public static string S_StudentImage {
            get {
                return ResourceManager.GetString("S_StudentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在抽取结果中显示学生头像.
        /// </summary>
        public static string S_StudentImage_D {
            get {
                return ResourceManager.GetString("S_StudentImage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像位置.
        /// </summary>
        public static string S_StudentImagePosition {
            get {
                return ResourceManager.GetString("S_StudentImagePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生头像相对文字的位置.
        /// </summary>
        public static string S_StudentImagePosition_D {
            get {
                return ResourceManager.GetString("S_StudentImagePosition_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 启用语音播报.
        /// </summary>
        public static string S_VoiceAnnouncementEnabled {
            get {
                return ResourceManager.GetString("S_VoiceAnnouncementEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 抽取完成后播报结果；全局语音播报开关关闭时，此设置不会生效。.
        /// </summary>
        public static string S_VoiceAnnouncementEnabled_D {
            get {
                return ResourceManager.GetString("S_VoiceAnnouncementEnabled_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画设置.
        /// </summary>
        public static string Section_Animation {
            get {
                return ResourceManager.GetString("Section_Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色设置.
        /// </summary>
        public static string Section_Color {
            get {
                return ResourceManager.GetString("Section_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示设置.
        /// </summary>
        public static string Section_Display {
            get {
                return ResourceManager.GetString("Section_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 抽取设置.
        /// </summary>
        public static string Section_Draw {
            get {
                return ResourceManager.GetString("Section_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖品图片设置.
        /// </summary>
        public static string Section_LotteryImage {
            get {
                return ResourceManager.GetString("Section_LotteryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐设置.
        /// </summary>
        public static string Section_Music {
            get {
                return ResourceManager.GetString("Section_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示语设置.
        /// </summary>
        public static string Section_Reminder {
            get {
                return ResourceManager.GetString("Section_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学生头像设置.
        /// </summary>
        public static string Section_StudentImage {
            get {
                return ResourceManager.GetString("Section_StudentImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 语音播报.
        /// </summary>
        public static string Section_VoiceAnnouncement {
            get {
                return ResourceManager.GetString("Section_VoiceAnnouncement", resourceCulture);
            }
        }
    }
}
