//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.SettingsPages.About {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecRandom.Langs.SettingsPages.About.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 复制用户信息.
        /// </summary>
        public static string C_CopyUserInformation {
            get {
                return ResourceManager.GetString("C_CopyUserInformation", resourceCulture);
            }
        }

        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }

        public static string C_InternalSettingsActivatedTitle {
            get {
                return ResourceManager.GetString("C_InternalSettingsActivatedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string C_Refresh {
            get {
                return ResourceManager.GetString("C_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 组织主页.
        /// </summary>
        public static string C_OrgHome {
            get {
                return ResourceManager.GetString("C_OrgHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 项目主页.
        /// </summary>
        public static string C_ProjectHome {
            get {
                return ResourceManager.GetString("C_ProjectHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 鸣谢.
        /// </summary>
        public static string S_Ack {
            get {
                return ResourceManager.GetString("S_Ack", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 贡献人员.
        /// </summary>
        public static string S_Ack_Contributors {
            get {
                return ResourceManager.GetString("S_Ack_Contributors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} 次提交.
        /// </summary>
        public static string S_Ack_Contributors_ContributionCount {
            get {
                return ResourceManager.GetString("S_Ack_Contributors_ContributionCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 查看为 SecRandom 提交代码的 GitHub 贡献者.
        /// </summary>
        public static string S_Ack_Contributors_D {
            get {
                return ResourceManager.GetString("S_Ack_Contributors_D", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to 无法加载贡献者名单：{0}.
        /// </summary>
        public static string M_ContributorsLoadFailed {
            get {
                return ResourceManager.GetString("M_ContributorsLoadFailed", resourceCulture);
            }
        }

        public static string M_InternalSettingsActivated {
            get {
                return ResourceManager.GetString("M_InternalSettingsActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用信息.
        /// </summary>
        public static string S_App {
            get {
                return ResourceManager.GetString("S_App", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用协议.
        /// </summary>
        public static string S_App_License {
            get {
                return ResourceManager.GetString("S_App_License", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 常用链接.
        /// </summary>
        public static string S_App_UsefulLinks {
            get {
                return ResourceManager.GetString("S_App_UsefulLinks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 应用作者.
        /// </summary>
        public static string S_Author {
            get {
                return ResourceManager.GetString("S_Author", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 哔哩哔哩.
        /// </summary>
        public static string S_Author_Bilibili {
            get {
                return ResourceManager.GetString("S_Author_Bilibili", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 访问 黎泽懿_Aionflux 的哔哩哔哩账号.
        /// </summary>
        public static string S_Author_BiliBili_D {
            get {
                return ResourceManager.GetString("S_Author_BiliBili_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 主开发者.
        /// </summary>
        public static string S_Author_D {
            get {
                return ResourceManager.GetString("S_Author_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 捐赠支持.
        /// </summary>
        public static string S_Author_Donate {
            get {
                return ResourceManager.GetString("S_Author_Donate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 访问 黎泽懿_Aionflux 的爱发电账号，支持项目发展，感谢您的捐赠.
        /// </summary>
        public static string S_Author_Donate_D {
            get {
                return ResourceManager.GetString("S_Author_Donate_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SECTL 思拓创联.
        /// </summary>
        public static string S_Author_Org {
            get {
                return ResourceManager.GetString("S_Author_Org", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SecRandom 所属组织.
        /// </summary>
        public static string S_Author_Org_D {
            get {
                return ResourceManager.GetString("S_Author_Org_D", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 黎泽懿_Aionflux.
        /// </summary>
        public static string S_Author_R {
            get {
                return ResourceManager.GetString("S_Author_R", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 用户信息.
        /// </summary>
        public static string S_UserInformation {
            get {
                return ResourceManager.GetString("S_UserInformation", resourceCulture);
            }
        }
    }
}
