//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecRandom.Langs.FirstRunOobe {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SecRandom.Langs.FirstRunOobe.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string GplNotice {
            get {
                return ResourceManager.GetString("GplNotice", resourceCulture);
            }
        }
        
        public static string C_Title {
            get {
                return ResourceManager.GetString("C_Title", resourceCulture);
            }
        }
        
        public static string C_Intro {
            get {
                return ResourceManager.GetString("C_Intro", resourceCulture);
            }
        }
        
        public static string C_WelcomeTitle {
            get {
                return ResourceManager.GetString("C_WelcomeTitle", resourceCulture);
            }
        }
        
        public static string C_WelcomeDescription {
            get {
                return ResourceManager.GetString("C_WelcomeDescription", resourceCulture);
            }
        }
        
        public static string C_Language {
            get {
                return ResourceManager.GetString("C_Language", resourceCulture);
            }
        }
        
        public static string C_LegalTitle {
            get {
                return ResourceManager.GetString("C_LegalTitle", resourceCulture);
            }
        }
        
        public static string C_LegalDescription {
            get {
                return ResourceManager.GetString("C_LegalDescription", resourceCulture);
            }
        }
        
        public static string C_PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("C_PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        public static string C_PrivacyPolicyAccept {
            get {
                return ResourceManager.GetString("C_PrivacyPolicyAccept", resourceCulture);
            }
        }
        
        public static string C_GplTitle {
            get {
                return ResourceManager.GetString("C_GplTitle", resourceCulture);
            }
        }
        
        public static string C_GplAccept {
            get {
                return ResourceManager.GetString("C_GplAccept", resourceCulture);
            }
        }
        
        public static string C_DataTitle {
            get {
                return ResourceManager.GetString("C_DataTitle", resourceCulture);
            }
        }
        
        public static string C_DataDescription {
            get {
                return ResourceManager.GetString("C_DataDescription", resourceCulture);
            }
        }
        
        public static string C_RestoreTitle {
            get {
                return ResourceManager.GetString("C_RestoreTitle", resourceCulture);
            }
        }
        
        public static string C_RestoreDescription {
            get {
                return ResourceManager.GetString("C_RestoreDescription", resourceCulture);
            }
        }
        
        public static string C_ImportSettings {
            get {
                return ResourceManager.GetString("C_ImportSettings", resourceCulture);
            }
        }
        
        public static string C_ImportAllData {
            get {
                return ResourceManager.GetString("C_ImportAllData", resourceCulture);
            }
        }
        
        public static string C_RollCallList {
            get {
                return ResourceManager.GetString("C_RollCallList", resourceCulture);
            }
        }
        
        public static string C_RollCallListDescription {
            get {
                return ResourceManager.GetString("C_RollCallListDescription", resourceCulture);
            }
        }
        
        public static string C_ImportRoster {
            get {
                return ResourceManager.GetString("C_ImportRoster", resourceCulture);
            }
        }
        
        public static string C_RefreshList {
            get {
                return ResourceManager.GetString("C_RefreshList", resourceCulture);
            }
        }
        
        public static string C_AddList {
            get {
                return ResourceManager.GetString("C_AddList", resourceCulture);
            }
        }
        
        public static string C_RenameList {
            get {
                return ResourceManager.GetString("C_RenameList", resourceCulture);
            }
        }
        
        public static string C_DeleteList {
            get {
                return ResourceManager.GetString("C_DeleteList", resourceCulture);
            }
        }
        
        public static string C_AddStudentListTitle {
            get {
                return ResourceManager.GetString("C_AddStudentListTitle", resourceCulture);
            }
        }
        
        public static string C_AddPrizeListTitle {
            get {
                return ResourceManager.GetString("C_AddPrizeListTitle", resourceCulture);
            }
        }
        
        public static string C_RenameListTitle {
            get {
                return ResourceManager.GetString("C_RenameListTitle", resourceCulture);
            }
        }
        
        public static string C_DeleteListTitle {
            get {
                return ResourceManager.GetString("C_DeleteListTitle", resourceCulture);
            }
        }
        
        public static string C_ListNameTitle {
            get {
                return ResourceManager.GetString("C_ListNameTitle", resourceCulture);
            }
        }
        
        public static string C_ListNamePlaceholder {
            get {
                return ResourceManager.GetString("C_ListNamePlaceholder", resourceCulture);
            }
        }
        
        public static string C_DefaultStudentListName {
            get {
                return ResourceManager.GetString("C_DefaultStudentListName", resourceCulture);
            }
        }
        
        public static string C_DefaultPrizeListName {
            get {
                return ResourceManager.GetString("C_DefaultPrizeListName", resourceCulture);
            }
        }
        
        public static string C_LotteryTitle {
            get {
                return ResourceManager.GetString("C_LotteryTitle", resourceCulture);
            }
        }
        
        public static string C_LotteryDescription {
            get {
                return ResourceManager.GetString("C_LotteryDescription", resourceCulture);
            }
        }
        
        public static string C_LotteryEnabled {
            get {
                return ResourceManager.GetString("C_LotteryEnabled", resourceCulture);
            }
        }
        
        public static string C_PrizeImport {
            get {
                return ResourceManager.GetString("C_PrizeImport", resourceCulture);
            }
        }
        
        public static string C_PrizeList {
            get {
                return ResourceManager.GetString("C_PrizeList", resourceCulture);
            }
        }
        
        public static string C_PrizeListDescription {
            get {
                return ResourceManager.GetString("C_PrizeListDescription", resourceCulture);
            }
        }
        
        public static string C_AppearanceTitle {
            get {
                return ResourceManager.GetString("C_AppearanceTitle", resourceCulture);
            }
        }
        
        public static string C_Theme {
            get {
                return ResourceManager.GetString("C_Theme", resourceCulture);
            }
        }
        
        public static string C_ThemeDescription {
            get {
                return ResourceManager.GetString("C_ThemeDescription", resourceCulture);
            }
        }
        
        public static string O_ThemeLight {
            get {
                return ResourceManager.GetString("O_ThemeLight", resourceCulture);
            }
        }
        
        public static string O_ThemeDark {
            get {
                return ResourceManager.GetString("O_ThemeDark", resourceCulture);
            }
        }
        
        public static string O_ThemeAuto {
            get {
                return ResourceManager.GetString("O_ThemeAuto", resourceCulture);
            }
        }
        
        public static string C_ThemeColor {
            get {
                return ResourceManager.GetString("C_ThemeColor", resourceCulture);
            }
        }
        
        public static string C_ThemeColorDescription {
            get {
                return ResourceManager.GetString("C_ThemeColorDescription", resourceCulture);
            }
        }
        
        public static string O_SystemColor {
            get {
                return ResourceManager.GetString("O_SystemColor", resourceCulture);
            }
        }
        
        public static string O_CustomColor {
            get {
                return ResourceManager.GetString("O_CustomColor", resourceCulture);
            }
        }
        
        public static string C_Opacity {
            get {
                return ResourceManager.GetString("C_Opacity", resourceCulture);
            }
        }
        
        public static string C_OpacityDescription {
            get {
                return ResourceManager.GetString("C_OpacityDescription", resourceCulture);
            }
        }
        
        public static string C_DesktopTitle {
            get {
                return ResourceManager.GetString("C_DesktopTitle", resourceCulture);
            }
        }
        
        public static string C_DesktopDescription {
            get {
                return ResourceManager.GetString("C_DesktopDescription", resourceCulture);
            }
        }
        
        public static string C_Autostart {
            get {
                return ResourceManager.GetString("C_Autostart", resourceCulture);
            }
        }
        
        public static string C_AutostartDescription {
            get {
                return ResourceManager.GetString("C_AutostartDescription", resourceCulture);
            }
        }
        
        public static string C_ShowStartupWindow {
            get {
                return ResourceManager.GetString("C_ShowStartupWindow", resourceCulture);
            }
        }
        
        public static string C_ShowStartupWindowDescription {
            get {
                return ResourceManager.GetString("C_ShowStartupWindowDescription", resourceCulture);
            }
        }
        
        public static string C_ExternalIntegration {
            get {
                return ResourceManager.GetString("C_ExternalIntegration", resourceCulture);
            }
        }
        
        public static string C_ExternalIntegrationDescription {
            get {
                return ResourceManager.GetString("C_ExternalIntegrationDescription", resourceCulture);
            }
        }
        
        
        public static string C_CompleteTitle {
            get {
                return ResourceManager.GetString("C_CompleteTitle", resourceCulture);
            }
        }
        
        public static string C_CompleteDescription {
            get {
                return ResourceManager.GetString("C_CompleteDescription", resourceCulture);
            }
        }
        
        public static string C_CompletedItems {
            get {
                return ResourceManager.GetString("C_CompletedItems", resourceCulture);
            }
        }
        
        public static string C_CompletedClass {
            get {
                return ResourceManager.GetString("C_CompletedClass", resourceCulture);
            }
        }
        
        public static string C_CompletedAppearance {
            get {
                return ResourceManager.GetString("C_CompletedAppearance", resourceCulture);
            }
        }
        
        public static string C_CompletedIntegration {
            get {
                return ResourceManager.GetString("C_CompletedIntegration", resourceCulture);
            }
        }
        
        
        public static string C_OverwriteTitle {
            get {
                return ResourceManager.GetString("C_OverwriteTitle", resourceCulture);
            }
        }
        
        public static string C_Overwrite {
            get {
                return ResourceManager.GetString("C_Overwrite", resourceCulture);
            }
        }
        
        public static string C_ResourcesTitle {
            get {
                return ResourceManager.GetString("C_ResourcesTitle", resourceCulture);
            }
        }
        
        public static string C_SectlWebsite {
            get {
                return ResourceManager.GetString("C_SectlWebsite", resourceCulture);
            }
        }
        
        public static string C_Documentation {
            get {
                return ResourceManager.GetString("C_Documentation", resourceCulture);
            }
        }
        
        public static string C_AuthorBilibili {
            get {
                return ResourceManager.GetString("C_AuthorBilibili", resourceCulture);
            }
        }
        
        public static string C_Sponsor {
            get {
                return ResourceManager.GetString("C_Sponsor", resourceCulture);
            }
        }
        
        public static string C_Community {
            get {
                return ResourceManager.GetString("C_Community", resourceCulture);
            }
        }
        
        public static string C_CommunityAnswer {
            get {
                return ResourceManager.GetString("C_CommunityAnswer", resourceCulture);
            }
        }
        
        public static string C_Previous {
            get {
                return ResourceManager.GetString("C_Previous", resourceCulture);
            }
        }
        
        public static string C_Start {
            get {
                return ResourceManager.GetString("C_Start", resourceCulture);
            }
        }
        
        public static string C_Next {
            get {
                return ResourceManager.GetString("C_Next", resourceCulture);
            }
        }
        
        public static string C_Finish {
            get {
                return ResourceManager.GetString("C_Finish", resourceCulture);
            }
        }
        
        public static string C_ImportSettingsTitle {
            get {
                return ResourceManager.GetString("C_ImportSettingsTitle", resourceCulture);
            }
        }
        
        public static string C_ImportAllDataTitle {
            get {
                return ResourceManager.GetString("C_ImportAllDataTitle", resourceCulture);
            }
        }
        
        public static string C_ImportTitle {
            get {
                return ResourceManager.GetString("C_ImportTitle", resourceCulture);
            }
        }
        
        public static string C_Import {
            get {
                return ResourceManager.GetString("C_Import", resourceCulture);
            }
        }
        
        public static string C_Cancel {
            get {
                return ResourceManager.GetString("C_Cancel", resourceCulture);
            }
        }
        
        public static string C_Close {
            get {
                return ResourceManager.GetString("C_Close", resourceCulture);
            }
        }
        
        public static string C_JsonFileType {
            get {
                return ResourceManager.GetString("C_JsonFileType", resourceCulture);
            }
        }
        
        public static string C_ZipFileType {
            get {
                return ResourceManager.GetString("C_ZipFileType", resourceCulture);
            }
        }
        
        public static string C_ExitTitle {
            get {
                return ResourceManager.GetString("C_ExitTitle", resourceCulture);
            }
        }
        
        public static string C_ExitDescription {
            get {
                return ResourceManager.GetString("C_ExitDescription", resourceCulture);
            }
        }
        
        public static string C_Exit {
            get {
                return ResourceManager.GetString("C_Exit", resourceCulture);
            }
        }
        
        public static string C_ContinueSetup {
            get {
                return ResourceManager.GetString("C_ContinueSetup", resourceCulture);
            }
        }
        
        public static string M_ImportConfirmation {
            get {
                return ResourceManager.GetString("M_ImportConfirmation", resourceCulture);
            }
        }
        
        public static string M_UnsupportedImportTitle {
            get {
                return ResourceManager.GetString("M_UnsupportedImportTitle", resourceCulture);
            }
        }
        
        public static string M_UnsupportedImport {
            get {
                return ResourceManager.GetString("M_UnsupportedImport", resourceCulture);
            }
        }
        
        public static string M_UnknownVersion {
            get {
                return ResourceManager.GetString("M_UnknownVersion", resourceCulture);
            }
        }
        
        public static string M_UnsupportedImportDetail {
            get {
                return ResourceManager.GetString("M_UnsupportedImportDetail", resourceCulture);
            }
        }
        
        public static string M_ImportCompleted {
            get {
                return ResourceManager.GetString("M_ImportCompleted", resourceCulture);
            }
        }
        
        public static string M_ImportFailed {
            get {
                return ResourceManager.GetString("M_ImportFailed", resourceCulture);
            }
        }
        
        public static string M_AgreementRequired {
            get {
                return ResourceManager.GetString("M_AgreementRequired", resourceCulture);
            }
        }
        
        public static string M_CompletionAgreementRequired {
            get {
                return ResourceManager.GetString("M_CompletionAgreementRequired", resourceCulture);
            }
        }
        
        public static string M_DesktopIntegrationFailed {
            get {
                return ResourceManager.GetString("M_DesktopIntegrationFailed", resourceCulture);
            }
        }
        
        public static string M_StudentsImported {
            get {
                return ResourceManager.GetString("M_StudentsImported", resourceCulture);
            }
        }
        
        public static string M_PrizesImported {
            get {
                return ResourceManager.GetString("M_PrizesImported", resourceCulture);
            }
        }
        
        public static string M_OverwriteListContent {
            get {
                return ResourceManager.GetString("M_OverwriteListContent", resourceCulture);
            }
        }
        
        public static string M_ListNameEmpty {
            get {
                return ResourceManager.GetString("M_ListNameEmpty", resourceCulture);
            }
        }
        
        public static string M_ListNameInvalid {
            get {
                return ResourceManager.GetString("M_ListNameInvalid", resourceCulture);
            }
        }
        
        public static string M_ListNameExists {
            get {
                return ResourceManager.GetString("M_ListNameExists", resourceCulture);
            }
        }
        
        public static string M_KeepOneList {
            get {
                return ResourceManager.GetString("M_KeepOneList", resourceCulture);
            }
        }
        
        public static string M_DeleteListContent {
            get {
                return ResourceManager.GetString("M_DeleteListContent", resourceCulture);
            }
        }
        
        public static string M_StepProgress {
            get {
                return ResourceManager.GetString("M_StepProgress", resourceCulture);
            }
        }
    }
}
